/**
 * https://medium.com/velotio-perspectives/how-to-write-jenkinsfile-for-angular-and-net-based-applications-1cbdbf56f906
 *
 * https://www.youtube.com/watch?v=7KCS70sCoK0&t=748s
 */

 //globall define
def gv
pipeline {
    //job agent
    agent { label "windows"}
    options {
        disableConcurrentBuilds()
    }
    //custom variables
    environment {
        START_TIME = new Date().format('yyyy-MM-dd HH:mm:ss')
        PROJECT_VERSION = '1.0.2'
    }
    stages {
        stage("init and Clean Workspace") {
            steps {
                script {
                    gv = load "script.groovy"
                }
                cleanWs()
            }
        }
        stage('Environment Setup') {
            parallel {
                stage('dev'){
                    when {
                        expression {
                            env.GIT_BRANCH == 'origin/dev'
                        }
                    }
                    environment {
                        //bind the credentials to your env variables
                        GSDS_DB_WEB_TEMP_CREDENTIALS = "My test credential. Shhh!"
                        
                    }
                    steps {
                        echo "building branch: ${BRANCH_NAME}"
                        script {
                            env.GSDS_DB_WEB_CREDENTIALS_PSW = "${GSDS_DB_WEB_TEMP_CREDENTIALS_PSW}"
                            env.DEPLOY_FQDN = 'somepath.com'
                            env.GSDS_CONFIG_FILE = 'dev.conf'
                        }
                    }
                }
                
            }
        }
        stage('Build') {
            steps {
                script {
                    gv.buildApp()
                }
            }
            
        }
    }
    post {
        failure {
            mail (to: 'lpedley@good-sam.com',
                 subject: "Job '${JOB_NAME}' (${BUILD_NUMBER}) Failed",
                 body: "Please go to ${BUILD_URL} and verify the build");
        }
    }
}
